# version: '3.8'


services:
  db:
    image: postgres:14
    container_name: shop-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop_network

  pdadmin:
    image: dpage/pgadmin4
    container_name: shop-pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5442:80"
    depends_on:
      - db
    networks:
      - shop_network

volumes:
  postgres_data:

networks:
  shop_network:
